# Use the official node.js image from the Docker Hub
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
 COPY . .

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"] 
